### ISSUE TITLE
Parser doesn't like float literals

### ISSUE THREAD

**Issue by ghost** [andersfr/zig-lsp#2]
The screenshot is self-explanatory:
![image](https://user-images.githubusercontent.com/21169548/64406764-4f3dea00-d08b-11e9-8ff9-de884ad50628.png)
```
dian@pc ~/p/zigtest> parser test.zig 
6:17-17 Line discarded from parse (unrecoverable error)
No errors
Duration: 0ms
```

**Comment by andersfr** [comment]
Fixed
